# This is a TEMPLATE file for new repositories
# Copy this to .github/workflows/claude-universal-fixer.yml in any new repo

name: 🤖 Universal Claude CI/CD Fixer
on:
  push:
    branches: [main, master, develop]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🔧 Universal Claude Fixer
        uses: anthropics/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            AUTO-DETECT AND FIX ALL ISSUES:
            1. Detect project type, language, and framework
            2. Fix all build, lint, test, and deployment errors
            3. Ensure the project builds and deploys successfully
            This is a universal fixer - work with ANY project type!